services:
  rabbitmq:
    image: rabbitmq:management
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
  frontend:
    build:
      context: ./finn.ui
      dockerfile: Dockerfile
    image: snailya2005/finn_frontend
    restart: always
    environment:
      - REACT_APP_BACKEND_URL=http://localhost
    command: npm run start
    ports:
      - "3000:3000"
  api:
    build:
      dockerfile: ./FINN.API/Dockerfile
    image: snailya2005/finn_api
    restart: always
    depends_on:
      - rabbitmq
    environment:
      - RabbitMQ__Uri=amqp://rabbitmq:5672
      - ConnectionStrings__SqliteConnection=Data Source=./sqlite/FINN.sqlite
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - /app/sqlite
      - tmp:/tmp
  reader:
    build:
      dockerfile: ./FINN.READER/Dockerfile
    image: snailya2005/finn_reader
    restart: always
    depends_on:
      - rabbitmq
    environment:
      - RabbitMQ__Uri=amqp://rabbitmq:5672
    volumes:
      - tmp:/tmp
  drafter:
    build:
      dockerfile: ./FINN.DRAFTER/Dockerfile
    image: snailya2005/finn_drafter
    restart: always
    depends_on:
      - rabbitmq
    environment:
      - RabbitMQ__Uri=amqp://rabbitmq:5672
      - ConnectionStrings__SqliteConnection=Data Source=./sqlite/FINN.sqlite
      - Storage=/app/data
    volumes:
      - /app/data
      - /app/sqlite
      - tmp:/tmp
volumes:
  tmp:
