services:
  # rabbitmq
  rabbitmq:
    image: rabbitmq:management
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"

  # frontend
  frontend:
    build:
      context: ./finn.ui
      dockerfile: Dockerfile
    image: snailya2005/finn_frontend
    restart: always
    environment:
      - REACT_APP_BACKEND_URL=http://localhost
    ports:
      - "3000:3000"
  
  # backend
  api:
    build:
      dockerfile: ./FINN.API/Dockerfile
    image: snailya2005/finn_api
    restart: always
    depends_on:
      - rabbitmq
    environment:
      - AllowedHosts=localhost # this should be set to server ip
      - RabbitMQ__Uri=amqp://rabbitmq:5672
      - ConnectionStrings__SqliteConnection=Data Source=./sqlite/api.sqlite
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - /app/sqlite
      - tmp:/tmp

  # microservice
  excel-service:
    build:
      dockerfile: ./FINN.EXCEL/Dockerfile
    image: snailya2005/finn_excel
    restart: always
    depends_on:
      - rabbitmq
    environment:
      - RabbitMQ__Uri=amqp://rabbitmq:5672
    volumes:
      - tmp:/tmp

  # microservice
  dxf-service:
    build:
      dockerfile: ./FINN.DXF/Dockerfile
    image: snailya2005/finn_dxf
    restart: always
    depends_on:
      - rabbitmq
    environment:
      - RabbitMQ__Uri=amqp://rabbitmq:5672
      - ConnectionStrings__SqliteConnection=Data Source=./sqlite/dxf.sqlite
      - Storage=/app/data
    volumes:
      - /app/data # save block dxf
      - /app/sqlite
      - tmp:/tmp

  # microservice
  cost-service:
    build:
      dockerfile: ./FINN.COST/Dockerfile
    image: snailya2005/finn_cost
    restart: always
    depends_on:
      - rabbitmq
    environment:
      - RabbitMQ__Uri=amqp://rabbitmq:5672
      - ConnectionStrings__SqliteConnection=Data Source=./sqlite/cost.sqlite
      - Storage=/app/data
    volumes:
      - /app/sqlite
      - tmp:/tmp

volumes:
  tmp:
